bool thisisabool

int8 thisisaint8

uint8 thisiauint8

int16 thisisaint16

uint16 thisisauint16

int32 thisisaint32

uint32 thisisauint32

int64 thisisaint64

uint64 thisisauint64

float32 thisafloat32

float64 thisisfloat64

#string thisisastring


#bool[] thisisaboolarray

int8[] thisisaint8array

#uint8[] thisiauint8array

#int16[] thisisaint16array

#uint16[] thisisauint16array

#int32[] thisisaint32array

#uint32[] thisisauint32array

#int64[] thisisaint64array

#uint64[] thisisauint64array

#float32[] thisafloat32array

#float64[] thisisfloat64array

#string[] thisisastringarrays

#builtin_interfaces/Time thisisatime

#builtin_interfaces/Time[] thisisatimearray




